### ISSUE TITLE
TODO - tweaks, issues, backlogs, misc. 

### ISSUE THREAD

**Issue by mjstealey** [fabric-testbed/artifact-manager#9]
- [x] display version URN as part of the UI output
- [x] add enable / disable button for version contents - not delete, but disable - only show disabled contents to authors
- [x] change delete to soft delete when using in production deployment

## Per Komal Slack message
- [x] Could we also enable deletion of an artifact from the GUI?
- [x] Searching artifacts today allows search on tag or title, can we allow to search based on a specific project?
- [x] Update Artifact via PUT returns 204 without json body however swagger says to expect 200
- [x] In order to differentiate the artifacts published by FABRIC (default examples)
    - Is it possible to enable special tag?
    - Another possibility I was thinking was published only from FABRIC Tutorial project
